SECTION "sram_a000", SRAM[$A000]
_SRAM_0_: db
_SRAM_1_: db
_SRAM_2_: db

SECTION "sram_a006", SRAM[$A006]
_SRAM_6_: db

SECTION "sram_a02a", SRAM[$A02A]
_SRAM_2A_: db

SECTION "sram_a1f5", SRAM[$A1F5]
_SRAM_1F5_: db

SECTION "sram_a1f9", SRAM[$A1F9]
_SRAM_1F9_: db

SECTION "sram_a221", SRAM[$A221]
_SRAM_221_: db
_SRAM_222_: db
_SRAM_223_: db

SECTION "sram_a231", SRAM[$A231]
_SRAM_231_: db

SECTION "sram_a233", SRAM[$A233]
_SRAM_233_: db

SECTION "sram_a235", SRAM[$A235]
_SRAM_235_: db

SECTION "sram_a238", SRAM[$A238]
_SRAM_238_: db

SECTION "sram_a9ef", SRAM[$A9EF]
_SRAM_9EF_: db
_SRAM_9F0_: db

SECTION "sram_a9fa", SRAM[$A9FA]
_SRAM_9FA_: db

SECTION "sram_aa04", SRAM[$AA04]
_SRAM_A04_: db
_SRAM_A05_: db

SECTION "sram_aa08", SRAM[$AA08]
_SRAM_A08_: db

SECTION "sram_aa12", SRAM[$AA12]
_SRAM_A12_: db

SECTION "sram_aa25", SRAM[$AA25]
_SRAM_A25_: db

SECTION "sram_c000", SRAM[$A000], BANK[1]
_SRAM_2000_: db
_SRAM_2001_: db
_SRAM_2002_: db

SECTION "sram_dfff", SRAM[$BFFF], BANK[1]
_SRAM_3FFF_: db

SECTION "sram_e000", SRAM[$A000], BANK[2]
maybe_database_init_flag__SRAM_A000_BANK_2_: db

SECTION "sram_e002", SRAM[$A002], BANK[2]
_SRAM_4002_: db

SECTION "sram_e02a", SRAM[$A02A], BANK[2]
_SRAM_402A_: db

SECTION "sram_10000", SRAM[$A000], BANK[3]
_SRAM_6000_: db

SECTION "sram_10006", SRAM[$A006], BANK[3]
_SRAM_6006_: db

SECTION "sram_10015", SRAM[$A015], BANK[3]
_SRAM_6015_: db

SECTION "sram_1002a", SRAM[$A02A], BANK[3]
_SRAM_602A_: db
_SRAM_602B_: db
_SRAM_602C_: db

SECTION "sram_10100", SRAM[$A100], BANK[3]
_SRAM_6100_: db
